# -*- coding: utf-8 -*-
"""Fine Tune Brain Tumor Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdb4sctkJnIP8xzXESkjt2pKpdCuKv4g
"""

# Install kagglehub for keyless dataset downloading, plus vision & visualization libraries
!pip install -q kagglehub opencv-python-headless scikit-learn seaborn matplotlib

import os
import sys
import random
import numpy as np
import cv2
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset, Subset
from torchvision import models, transforms
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
import kagglehub

# ----- Seed & Device Setup -----
def set_seed(seed=42):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True

set_seed(42)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

# ----- Hyperparameters -----
IMG_SIZE = 224
BATCH_SIZE = 32
ARCHITECTURE = "resnet50"

HEAD_EPOCHS = 5
HEAD_LR = 1e-3
FINETUNE_EPOCHS = 8
FINETUNE_LR = 1e-4
OUTPUT_DIR = "/content"

print("Downloading Brain Tumor MRI dataset via kagglehub...")
# Downloads dataset automatically to Colab cache without needing Kaggle API credentials
DATA_DIR = kagglehub.dataset_download("masoudnickparvar/brain-tumor-mri-dataset")

train_dir = os.path.join(DATA_DIR, "Training")
test_dir = os.path.join(DATA_DIR, "Testing")

class_names = sorted(os.listdir(train_dir))
print("Data Directory:", DATA_DIR)
print("Classes found:", class_names)

# Check class distribution
counts = {c: len(os.listdir(os.path.join(train_dir, c))) for c in class_names}
plt.figure(figsize=(7, 4))
plt.bar(counts.keys(), counts.values(), color="steelblue")
plt.title("Training Images Per Class")
plt.ylabel("Count")
plt.show()

# Sample image preview
fig, axes = plt.subplots(1, len(class_names), figsize=(4 * len(class_names), 4))
for ax, c in zip(axes, class_names):
    c_dir = os.path.join(train_dir, c)
    sample_file = os.listdir(c_dir)[0]
    img = Image.open(os.path.join(c_dir, sample_file))
    ax.imshow(img, cmap="gray")
    ax.set_title(c)
    ax.axis("off")
plt.tight_layout()
plt.show()

import numpy as np
import torch
from torch.utils.data import DataLoader, Subset
from torchvision import transforms
from torchvision.datasets import ImageFolder  # Correct import for ImageFolder
from sklearn.model_selection import train_test_split

# Data Augmentations and Normalization
train_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.RandomRotation(degrees=15),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

eval_transform = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

# Create ImageFolder datasets directly from torchvision.datasets
full_train_dataset = ImageFolder(train_dir, transform=train_transform)
test_dataset = ImageFolder(test_dir, transform=eval_transform)

# Perform 85/15 Stratified Train/Validation split on Training directory
targets = full_train_dataset.targets
train_idx, val_idx = train_test_split(
    np.arange(len(targets)), test_size=0.15, random_state=42, stratify=targets
)

train_dataset = Subset(full_train_dataset, train_idx)
# Use eval_transform for validation dataset
val_dataset_base = ImageFolder(train_dir, transform=eval_transform)
val_dataset = Subset(val_dataset_base, val_idx)

# DataLoaders
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader = DataLoader(test_dataset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

# Compute class weights for imbalanced cross-entropy loss
class_counts = np.bincount([targets[i] for i in train_idx])
total_samples = len(train_idx)
class_weights = total_samples / (len(class_names) * class_counts)
class_weights_tensor = torch.tensor(class_weights, dtype=torch.float32).to(device)

print(f"Train batches: {len(train_loader)} | Val batches: {len(val_loader)} | Test batches: {len(test_loader)}")
print("Class weights:", class_weights_tensor.cpu().numpy())

def build_model(num_classes=4):
    weights = models.ResNet50_Weights.DEFAULT
    model = models.resnet50(weights=weights)

    # Freeze backbone initially
    for param in model.parameters():
        param.requires_grad = False

    # Replace final classification head
    in_features = model.fc.in_features
    model.fc = nn.Sequential(
        nn.Dropout(0.3),
        nn.Linear(in_features, num_classes)
    )
    return model

def unfreeze_layer4(model):
    # Unfreeze final residual block (layer4) and classification head
    for param in model.layer4.parameters():
        param.requires_grad = True
    for param in model.fc.parameters():
        param.requires_grad = True
    return model

def count_params(model):
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total = sum(p.numel() for p in model.parameters())
    return trainable, total

model = build_model(num_classes=len(class_names)).to(device)
trainable, total = count_params(model)
print(f"Phase 1 - Trainable parameters: {trainable:,} / {total:,}")

def train_model(model, train_loader, val_loader, epochs, lr, class_weights):
    criterion = nn.CrossEntropyLoss(weight=class_weights)
    optimizer = optim.AdamW(filter(lambda p: p.requires_grad, model.parameters()), lr=lr, weight_decay=1e-4)

    history = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

    for epoch in range(epochs):
        # Training Phase
        model.train()
        running_loss, correct, total = 0.0, 0, 0
        for inputs, labels in train_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            optimizer.zero_grad()

            outputs = model(inputs)
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item() * inputs.size(0)
            _, preds = torch.max(outputs, 1)
            correct += (preds == labels).sum().item()
            total += labels.size(0)

        epoch_train_loss = running_loss / total
        epoch_train_acc = correct / total

        # Validation Phase
        model.eval()
        val_loss, val_correct, val_total = 0.0, 0, 0
        with torch.no_grad():
            for inputs, labels in val_loader:
                inputs, labels = inputs.to(device), labels.to(device)
                outputs = model(inputs)
                loss = criterion(outputs, labels)

                val_loss += loss.item() * inputs.size(0)
                _, preds = torch.max(outputs, 1)
                val_correct += (preds == labels).sum().item()
                val_total += labels.size(0)

        epoch_val_loss = val_loss / val_total
        epoch_val_acc = val_correct / val_total

        history['train_loss'].append(epoch_train_loss)
        history['train_acc'].append(epoch_train_acc)
        history['val_loss'].append(epoch_val_loss)
        history['val_acc'].append(epoch_val_acc)

        print(f"Epoch {epoch+1:02d}/{epochs:02d} | "
              f"Train Loss: {epoch_train_loss:.4f} - Train Acc: {epoch_train_acc:.4f} | "
              f"Val Loss: {epoch_val_loss:.4f} - Val Acc: {epoch_val_acc:.4f}")

    return model, history

def plot_curves(h1, h2=None):
    fig, axes = plt.subplots(1, 2, figsize=(12, 4))

    t_loss = h1['train_loss'] + (h2['train_loss'] if h2 else [])
    v_loss = h1['val_loss'] + (h2['val_loss'] if h2 else [])
    t_acc = h1['train_acc'] + (h2['train_acc'] if h2 else [])
    v_acc = h1['val_acc'] + (h2['val_acc'] if h2 else [])

    axes[0].plot(t_loss, label='Train Loss')
    axes[0].plot(v_loss, label='Val Loss')
    if h2:
        axes[0].axvline(x=len(h1['train_loss'])-1, color='gray', linestyle='--', label='Phase 2 Start')
    axes[0].set_title('Loss Curves')
    axes[0].set_xlabel('Epoch')
    axes[0].legend()

    axes[1].plot(t_acc, label='Train Acc')
    axes[1].plot(v_acc, label='Val Acc')
    if h2:
        axes[1].axvline(x=len(h1['train_acc'])-1, color='gray', linestyle='--', label='Phase 2 Start')
    axes[1].set_title('Accuracy Curves')
    axes[1].set_xlabel('Epoch')
    axes[1].legend()

    plt.tight_layout()
    plt.show()

print("--- Phase 1: Training Classification Head ---")
model, history1 = train_model(
    model, train_loader, val_loader,
    epochs=HEAD_EPOCHS, lr=HEAD_LR, class_weights=class_weights_tensor
)

print("\n--- Phase 2: Fine-Tuning Last Block (layer4) ---")
model = unfreeze_layer4(model)
trainable, total = count_params(model)
print(f"Phase 2 - Trainable parameters: {trainable:,} / {total:,}")

model, history2 = train_model(
    model, train_loader, val_loader,
    epochs=FINETUNE_EPOCHS, lr=FINETUNE_LR, class_weights=class_weights_tensor
)

plot_curves(history1, history2)

model.eval()
all_preds, all_targets = [], []

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs = inputs.to(device)
        outputs = model(inputs)
        _, preds = torch.max(outputs, 1)

        all_preds.extend(preds.cpu().numpy())
        all_targets.extend(labels.numpy())

# Classification Report
print("\nClassification Report:")
print(classification_report(all_targets, all_preds, target_names=class_names))

# Confusion Matrix Plot
cm = confusion_matrix(all_targets, all_preds)
plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('Test Set Confusion Matrix')
plt.xlabel('Predicted Class')
plt.ylabel('True Class')
plt.show()

class GradCAM:
    def __init__(self, model, target_layer):
        self.model = model
        self.target_layer = target_layer
        self.gradients = None
        self.activations = None

        target_layer.register_forward_hook(self._forward_hook)
        target_layer.register_full_backward_hook(self._backward_hook)

    def _forward_hook(self, module, input, output):
        self.activations = output

    def _backward_hook(self, module, grad_input, grad_output):
        self.gradients = grad_output[0]

    def generate_heatmap(self, input_tensor, class_idx=None):
        self.model.eval()
        output = self.model(input_tensor)

        if class_idx is None:
            class_idx = output.argmax(dim=1).item()

        self.model.zero_grad()
        score = output[0, class_idx]
        score.backward()

        gradients = self.gradients.data.cpu().numpy()[0]
        activations = self.activations.data.cpu().numpy()[0]

        weights = np.mean(gradients, axis=(1, 2))
        cam = np.zeros(activations.shape[1:], dtype=np.float32)

        for i, w in enumerate(weights):
            cam += w * activations[i]

        cam = np.maximum(cam, 0)
        if cam.max() > 0:
            cam = cam / cam.max()

        return cv2.resize(cam, (IMG_SIZE, IMG_SIZE)), class_idx

# Overlay Heatmap onto RGB Image
def overlay_cam(pil_img, heatmap):
    img_np = np.array(pil_img.resize((IMG_SIZE, IMG_SIZE)))
    heatmap_colored = cv2.applyColorMap(np.uint8(255 * heatmap), cv2.COLORMAP_JET)
    heatmap_colored = cv2.cvtColor(heatmap_colored, cv2.COLOR_BGR2RGB)

    overlay = cv2.addWeighted(img_np, 0.6, heatmap_colored, 0.4, 0)
    return overlay

# Run Grad-CAM on one sample scan per class
cam = GradCAM(model, model.layer4[-1])
fig, axes = plt.subplots(1, len(class_names), figsize=(4 * len(class_names), 4))

for ax, c in zip(axes, class_names):
    c_dir = os.path.join(test_dir, c)
    sample_path = os.path.join(c_dir, os.listdir(c_dir)[0])

    pil_img = Image.open(sample_path).convert('RGB')
    input_tensor = eval_transform(pil_img).unsqueeze(0).to(device)

    heatmap, pred_idx = cam.generate_heatmap(input_tensor)
    overlay = overlay_cam(pil_img, heatmap)

    ax.imshow(overlay)
    ax.set_title(f"True: {c}\nPred: {class_names[pred_idx]}")
    ax.axis('off')

plt.tight_layout()
plt.show()

# 1. Save Fine-Tuned Model Weights
checkpoint_path = os.path.join(OUTPUT_DIR, f"brain_tumor_{ARCHITECTURE}.pt")
torch.save({
    'model_state_dict': model.state_dict(),
    'class_names': class_names,
    'architecture': ARCHITECTURE
}, checkpoint_path)
print("Saved fine-tuned checkpoint to:", checkpoint_path)

# 2. Single Image Inference Pipeline
def predict_single_image(image_path, model, class_names):
    pil_img = Image.open(image_path).convert('RGB')
    input_tensor = eval_transform(pil_img).unsqueeze(0).to(device)

    model.eval()
    with torch.no_grad():
        outputs = model(input_tensor)
        probs = torch.softmax(outputs, dim=1)[0].cpu().numpy()

    pred_idx = np.argmax(probs)
    return {
        'predicted_class': class_names[pred_idx],
        'confidence': float(probs[pred_idx]),
        'all_probabilities': {name: float(p) for name, p in zip(class_names, probs)}
    }

# Test inference on a single sample image
sample_test_img = os.path.join(test_dir, class_names[0], os.listdir(os.path.join(test_dir, class_names[0]))[0])
result = predict_single_image(sample_test_img, model, class_names)

print(f"\nInference Test on '{sample_test_img}':")
print(f"Predicted Class: {result['predicted_class']} (Confidence: {result['confidence']:.4f})")
print("Class Probabilities:")
for name, prob in result['all_probabilities'].items():
    print(f"  - {name}: {prob:.4f}")



